export const FIELD_LABELS = {
    by: 'by',
    app_title: 'The Library of the Israeli Community of Madrid',
    title: "Book Title",
    author: "Author",
    description: "Description",
    year_of_publication: "Year of Publication",
    cover_type: "Cover Type",
    pages: "Pages",
    borrowing_child: "Borrowing Child's Name",
    borrowed_by: "Borrowed By",
    borrower: "Borrower",
    borrow: "Borrow Book",
    delivery_status: "Delivery Status",
    delivering_parent: "Delivering Parent",
    recommended_age: "Recommended Age",
    borrow_date: "Borrow Date",
    return_date: "Return Date",
    NotReturned: "Not Returned",
    add_book_label: "Add New Book",
    books: "Books",
    members: "Members",
    loans: "Loans",
    ShowAllLoans: "Show History",
    Hide_Details: "Hide Details",
    More_Details: "More Details",
    loan_status: "Availability",
    sort_by: "Sort By",
    ascending: "Ascending",
    descending: "Descending",
    Hide_Add_Book: "Hide Add Book",
    Add_Book: "Add Book",
    return: "Return Book",
    Select_Book: "Select Book",
    Select_Book_State: "Select Book State",
    ScanQR: "Scan QR Code",
    download_qr_code: "Download QR Code",
    SendReminders: "Send Reminders",
    last_reminder: "last reminder at",
    error_generating_report: "Failed to generate report. Please try again.",
    reports: "Reports",
    generate_report_button: "Generate report",
    select_borrower: 'Select Borrower',

    // General Labels
    add_member_button: 'Add Member',
    close_add_member_button: 'Close Add Member',
    add_member_form_title: 'Add New Member',
    search_placeholder: 'Search members by name',
    members_list_title: 'Library Members',
    no_members_found: 'No members found',

    // Form Placeholders and Labels
    parent_name_placeholder: 'Parent\'s Name',
    kid_name_placeholder: 'Kid\'s Name',
    email_placeholder: 'Email Address',

    // Form Error Messages
    error_parent_name_required: 'Parent\'s name is required.',
    error_kid_name_required: 'Kid\'s name is required.',
    error_email_required: 'Email address is required.',
    error_email_invalid: 'Invalid email address.',

    // Success Messages
    success_member_added: 'Member added successfully!',

    // List Item Labels
    parent_name_label: 'Parent Name',
    kid_name_label: 'Child Name',
    email_label: 'Email',

    // New Labels for Inventory
    // UI Labels
    inventory_list_title: 'Library Inventory',
    add_book_button: 'Add Book',
    close_add_book_button: 'Close Add Book',
    search_books_placeholder: 'Search books by title',
    no_books_found: 'No books found',

    // Field Placeholders
    placeholder_book_title: 'Enter Book Title',
    placeholder_book_author: 'Enter Author Name',
    placeholder_book_description: 'Enter Description',
    placeholder_book_year: 'Enter Year of Publication',
    placeholder_book_pages: 'Enter Number of Pages',
    placeholder_book_recommended_age: 'Enter Recommended Age',
    select_condition: 'Select Condition',
    select_loan_status: 'Select loan status',
    select_parent: 'Select Parent',
    select_cover_type: 'format',

    // ENUM Options for Drop-Downs
    soft_cover: 'Soft Cover',
    hard_cover: 'Hard Cover',
    rigid_pages: 'Rigid Pages',
    battery_book: 'Book with Battery',
    new: 'New',
    good: 'Good',
    worn: 'Worn',
    available: 'Available',
    borrowed: 'Borrowed',

    // Validation Errors
    error_book_title_required: 'Book title is required.',
    error_book_author_required: 'Author name is required.',
    error_book_description_required: 'Description is required.',
    error_book_year_required: 'Year of publication is required.',
    error_book_pages_required: 'Number of pages is required.',

    // Report labels
    inventory_report: 'Inventory Report',
    loans_report: 'Loans Report',
    select_report_type: 'Select Report Type',
    report_options: 'Report Options',
    select_field: 'Select Field',
    book_title: 'Book Title',
    id: 'ID',
    order: 'Order',
    include_history: 'Include Historical Loans',
    include_borrowed: 'Include Currently Borrowed Books',
};
