export const FIELD_LABELS = {
    by: 'על ידי',
    app_title: 'ספריית הקהילה הישראלית במדריד',
    title: "שם הספר",
    author: "שם המחבר",
    description: "תיאור",
    year_of_publication: "שנת הוצאה",
    cover_type: "סוג כריכה",
    pages: "עמודים",
    borrowing_child: "שם הילד המשאיל",
    borrowed_by: "הושאל על ידי",
    borrower: "המשאיל",
    borrow: "השאל ספר",
    delivery_status: "מצב מסירה",
    delivering_parent: "שם ההורה המוסר",
    recommended_age: "גיל מומלץ",
    borrow_date: "תאריך השאלה",
    return_date: "תאריך החזרה",
    NotReturned: "לא הוחזר",
    add_book_label: "הוסף ספר חדש",
    books: "ספרים",
    members: "חברים",
    loans: "השאלות",
    ShowAllLoans: "הצג היסטוריה",
    Hide_Details: "הסתר פרטים",
    More_Details: "עוד פרטים",
    loan_status:   "זמינות",
    sort_by: "סדר לפי",
    ascending: "עולה",
    descending: "יורד",
    Hide_Add_Book: "הסתר הוספת ספר",
    Add_Book: "הוסף ספר",
    return: "החזר ספר",
    Select_Book: "בחר ספר",
    Select_Book_State: "מצב הספר",
    ScanQR: "סרוק ברקוד",
    download_qr_code: "הורד ברקוד",
    SendReminders: "שלח תזכורת",
    last_reminder: "תזכורת אחרונה ב",
    no_reminder_sent: "לא נשלחה תזכורת",
    sending_reminders: "שולח...",
    send_x_reminders: "שלח {count} תזכורות",
    error_generating_report: "הפקת הדוח נכשלה, נסה שנית בבקשה.",
    reports: "דוחות",
    generate_report_button: "הפק דוח",
    select_borrower: "בחר משאיל",

    // General Labels
    add_member_button: 'הוסף חבר',
    edit_member: 'ערוך',
    delete_member: 'מחק חבר',
    close_add_member_button: 'סגור הוספת חבר',
    add_member_form_title: 'הוספת חבר חדש',
    search_placeholder: 'חפש חברים לפי שם',
    members_list_title: 'חברי הספרייה',
    no_members_found: 'לא נמצאו חברים',
    select_all: 'בחר הכל',

    // Form Placeholders and Labels
    parent_name_placeholder: 'שם ההורה המשאיל',
    kid_name_placeholder: 'שם הילד המשאיל',
    parent_name_borrower: 'ההורה',
    kid_name_borrower: 'הילד',
    email_placeholder: 'כתובת אימייל',

    // Form Error Messages
    error_parent_name_required: 'נדרש שם הורה.',
    error_kid_name_required: 'נדרש שם ילד.',
    error_email_required: 'נדרשת כתובת אימייל.',
    error_email_invalid: 'כתובת אימייל לא תקינה.',
    email_missing_warning: 'לא סופק אימייל - לא יישלחו התראות לחבר זה',
    no_email_provided: 'לא סופק אימייל',

    // Success Messages
    success_member_added: 'החבר נוסף בהצלחה!',
    success_member_updated: 'החבר עודכן בהצלחה!',
    success_member_deleted: 'חבר נמחק בהצלחה!',


    // List Item Labels
    parent_name_label: 'שם ההורה',
    kid_name_label: 'שם הילד',
    email_label: 'אימייל',

    // New Labels for Inventory
    // UI Labels
    inventory_list_title: 'מלאי הספרייה',
    add_book_button: 'הוסף ספר',
    close_add_book_button: 'סגור הוספת ספר',
    search_books_placeholder: 'חפש ספרים לפי שם',
    no_books_found: 'לא נמצאו ספרים',

    // Field Placeholders
    placeholder_book_title: 'הכנס שם הספר',
    placeholder_book_author: 'הכנס שם המחבר',
    placeholder_book_description: 'הכנס תיאור',
    placeholder_book_year: 'הכנס שנת הוצאה',
    placeholder_book_pages: 'הכנס מספר עמודים',
    placeholder_book_recommended_age: 'הכנס גיל מומלץ',
    select_condition: 'מצב מסירה',
    select_loan_status: 'זמינות',
    select_parent: 'שם ההורה',
    select_cover_type: "פורמט",

    // ENUM Options for Drop-Downs
    soft_cover: 'כריכה רכה',
    hard_cover: 'כריכה קשה',
    rigid_pages: 'עמודים קשיחים',
    battery_book: 'ספר עם בטריה',
    new: 'כמו חדש',
    good: 'מצויין - בלאי בלתי מורגש',
    worn: 'טוב - בלאי קל',
    available: 'זמין',
    borrowed: 'מושאל',

    // Validation Errors
    error_book_title_required: 'נדרש שם ספר.',
    error_book_author_required: 'נדרש שם מחבר.',
    error_book_description_required: 'נדרש תיאור.',
    error_book_year_required: 'נדרשת שנת הוצאה.',
    error_book_pages_required: 'נדרש מספר עמודים.',
    confirm_delete_member: 'האם אתה בטוח שברצונך למחוק חבר זה?',

    // Reports labels
    inventory_report: 'דוח מלאי',
    loans_report: 'דוח השאלות',
    select_report_type: 'בחר סוג דוח',
    report_options: 'אפשרויות דוח',
    select_field: 'בחר שדה',
    book_title: 'כותרת הספר',
    id: 'מזהה',
    order: 'סדר',
    include_history: 'כלול היסטורית השאלות',
    include_borrowed: 'כלול ספרים מושאלים',
    update_book_button: 'עדכון ספר',
    edit_book: 'ערוך ספר',

    // Login screen
    login_title: "כניסה לספרייה",
    username: "שם משתמש",
    password: "סיסמה",
    username_placeholder: "הכנס שם משתמש",
    password_placeholder: "הכנס סיסמה",
    login_button: "כניסה",
    logging_in: "מתחבר...",
    invalid_credentials: "שם משתמש או סיסמה לא נכונים.",

    qr_codes_report: "הדפס קודי QR",
    qr_codes_available: "ישנם {count} קודי QR זמינים.",
    qr_codes_description: "דוח זה יפיק קובץ PDF להדפסה של קודי QR המסודרים ברשת עם קווים לחיתוך.",
    inventory_report_description: "דוח זה מייצר קובץ Excel עם פרטי המלאי הנוכחי. ניתן למיין את הנתונים לפי שדות שונים ולבחור לכלול פריטים מושאלים.",
    loans_report_description: "דוח זה מייצר קובץ Excel של הלוואות פעילות. ניתן לבחור לכלול הלוואות היסטוריות ולמיין לפי שדות שונים.",
    start_qr: "ממזהה QR",
    end_qr: "עד מזהה QR",
    end_qr_exceed_error: "מספר ה-QR הסופי לא יכול להיות גדול מ-{qrCount}.",
    from_qr_greater_error: "מספר ה-QR ההתחלתי לא יכול להיות גדול ממספר ה-QR הסופי.",
};
